# Generated by Django 2.1.2 on 2018-10-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20180928_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='value',
            field=models.ImageField(upload_to='images/%y/%m/%d/'),
        ),
    ]
