# Generated by Django 2.0.3 on 2018-09-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
